# Generated by Django 5.0.3 on 2024-03-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_updatedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedetails',
            name='week',
            field=models.CharField(choices=[('Week1', 'Week1'), ('Week2', 'Week2'), ('Week3', 'Week3'), ('Week4', 'Week4'), ('Week5', 'Week5')], max_length=50),
        ),
    ]
